# Generated by Django 5.1.3 on 2024-11-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_payment_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phonenumber',
            field=models.CharField(error_messages={'invalid': 'Неверный телефонный номер'}, max_length=70, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_content',
            field=models.CharField(error_messages={'invalid': 'Ошибка в данных'}, max_length=200, verbose_name='Данные адреса доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_content',
            field=models.CharField(error_messages={'invalid': 'Ошибка в заказе'}, max_length=2000, verbose_name='Данные заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person_content',
            field=models.CharField(error_messages={'invalid': 'Ошибка в данных'}, max_length=200, verbose_name='Данные пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(error_messages={'invalid': 'Неверный телефонный номер'}, max_length=70, verbose_name='Телефонный номер'),
        ),
    ]
